language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls -v

script: composer test
